### PR TITLE
Vbcc 0.9e, VLink 0.15d, VAsm 0.17h

### PR DESCRIPTION
**Pull request by tehKaiN**
I've updated toolchain executables to latest versions.

Also, I've tweaked README.md to let ppl know how to do future updates themselves, so pull requests like this could appear more frequently.

### CODE REVIEW

**Review by kusma — APPROVED** [review]
Nice!

**Comment by midwan** [comment]
Nice one! I'll make sure to update the guide regarding your notes in the Readme also! :)

**Comment by midwan** [comment]
@tehKaiN 
Could you please explain why you needed to take away the CC options from the Makefile? Did you run into any problems with them?

**Comment by midwan** [comment]
I've updated the guide on BlitterStudio, so the right endianess shows in the answers now.

**Comment by tehKaiN** [comment]
@midwan I've assumed that -DHAVE_AOS4 may do something nasty when compiling cross-compiler for 68k. If it doesn't interfere with anyting, this step is not needed.

ED: Now I see that it refers to ifdef sections without elses, so this switch is prob'ly harmless.

**Comment by midwan** [comment]
@tehKaiN 
But in the article it mentions that you should replace it:

Replace the second line from this:
`CC = gcc -std=c9x -g -DHAVE_AOS4 #-DHAVE_ECPP -DHAVE_MISRA`
To this:

`CC = cl /D_CRT_SECURE_NO_WARNINGS /nologo /O2 /MT /Zp1 /wd4715 /wd4068 /wd4048`

In your readme, you mention that you deleted everything from there, that's why I asked: did the options I suggested above give you any trouble?

**Comment by tehKaiN** [comment]
I've used mingw, not visual c, so didn't have to replace with this line.
Generally during compilation I've tweaked makefiles a bit so that cl 
wouldn't be needed.

W dniu 2017-03-02 o 19:09, Dimitris Panokostas pisze:

**Comment by midwan** [comment]
Ah, ok then. I was a bit curious about it... :)

**Comment by midwan** [comment]
@tehKaiN @kusma 
Might I suggest that we update the README accordingly then? If people follow the guide on BlitterStudio, then the right instructions are already there (if they use Visual Studio). Perhaps we can have an extra paragraph for people using MinGW also.

**Comment by tehKaiN** [comment]
Of course, I think it's right thing to do.

W dniu 2017-03-04 o 17:26, Dimitris Panokostas pisze:

**Comment by kusma** [comment]
@midwan: Patches welcome :)

**Comment by midwan** [comment]
@kusma 
You have incoming... :)

**Pull request merged**
